import Sidebar from "@/components/layout/Sidebar";
import Navbar from "@/components/layout/Navbar";
import ConditionalFooter from "@/components/layout/ConditionalFooter";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { getCurrentUser } from "@/lib/auth";
import prisma from "@/lib/db";
import NextTopLoader from "nextjs-toploader";
import { ensureUserProfile } from "@/lib/users";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { AppProviders } from "@/components/interactions/AppProviders";
import {
  InertWhenDrawerOpen,
  NavigationDrawerProvider,
} from "@/components/layout/NavigationDrawerProvider";
import { getUnreadCounts } from "@/app/actions/messages";
import { cookies, headers } from "next/headers";
import { createClient } from "@/utils/supabase/server";
import { IOS_STARTUP_IMAGES } from "@/lib/ios-startup-images";
import { redirect } from "next/navigation";
import { SEO_SITE } from "@/constants/seo";

// In app/layout.tsx or your root SEO metadata config
const isDev =
  process.env.NEXT_PUBLIC_SITE_URL?.includes("dev.scholarbase.app") ||
  process.env.VERCEL_ENV !== "production";

// Captures `beforeinstallprompt` before React can possibly hydrate.
//
// This event fires ONCE per page load, and on a fast load it can fire BEFORE
// React hydrates and `PwaInstallProvider` attaches its `useEffect` listener.
// The event is not re-issued, so a late listener misses it forever: the install
// button would then show "How to install" until a reload that happened to be
// slower, which is exactly the non-deterministic behaviour this avoids.
//
// This inline script is the earliest code we control, so it always wins the
// race. It stashes the event on `window`, and the provider picks it up on mount
// (or later, if the event has not fired yet). No `async`/`defer`, no import: it
// must run synchronously in `<head>`.
const INSTALL_PROMPT_CAPTURE = `
(function () {
  if (window.__sbInstallPrompt) return;
  window.__sbInstallPrompt = null;
  window.addEventListener("beforeinstallprompt", function (e) {
    e.preventDefault();
    window.__sbInstallPrompt = e;
    window.dispatchEvent(new Event("sb:beforeinstallprompt"));
  });
  window.addEventListener("appinstalled", function () {
    window.__sbInstallPrompt = null;
    window.dispatchEvent(new Event("sb:appinstalled"));
  });
})();
`;

export const metadata: Metadata = {
  metadataBase: new URL(SEO_SITE.url),
  title: SEO_SITE.title.default,
  description: SEO_SITE.description,
  keywords: SEO_SITE.keywords,
  authors: SEO_SITE.authors,
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: SEO_SITE.name,
    title: SEO_SITE.title.default,
    description: SEO_SITE.openGraphDescription,
    url: SEO_SITE.url,
    images: [
      {
        url: SEO_SITE.defaultImage,
        width: 1200,
        height: 630,
        alt: SEO_SITE.imageAlt,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: SEO_SITE.twitterTitle,
    description: SEO_SITE.twitterDescription,
    images: [SEO_SITE.defaultImage],
  },
  alternates: {
    canonical: SEO_SITE.url,
  },
  category: SEO_SITE.category,
  manifest: "/manifest.json",
  appleWebApp: {
    title: "ScholarBase",
    capable: true,
    // iOS does not read `background_color` from the manifest for the splash
    // screen -- it ignores the manifest entirely and only honours
    // `<link rel="apple-touch-startup-image">`. Without these, a Home Screen
    // install boots to a blank white screen on every iPhone and iPad.
    //
    // `statusBarStyle` is left at its default ("default") deliberately.
    // "black-translucent" is the usual advice, but it makes the web view extend
    // under the status bar and the notch, which then overlaps the Navbar --
    // this app has no `env(safe-area-inset-*)` padding anywhere, so adopting it
    // would trade a white splash for a broken header.
    //
    // Generated by scripts/generate-ios-splash.py; see that module's header.
    startupImage: IOS_STARTUP_IMAGES,
  },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon.png", sizes: "48x48", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  robots: isDev
    ? {
        index: false,
        follow: false,
      }
    : {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          "max-image-preview": "large",
          "max-video-preview": -1,
          "max-snippet": -1,
        },
      },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#020617" },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Defer auth resolution so the Navbar/Sidebar render immediately with a
  // logged-out shell while Supabase auth resolves in the background. This
  // keeps the page responsive on slow mobile connections instead of blocking
  // the entire render behind `getCurrentUser()`.
  const userPromise = getCurrentUser();

  const cookieStore = await cookies();
  // The per-request CSP nonce, generated in `src/proxy.ts` and forwarded on the
  // request headers. It must match the `nonce-` in the policy exactly, or this
  // script — and Next's own bootstrap scripts — get blocked once the policy is
  // switched to enforcing. Undefined during static generation, which is exactly
  // when no CSP header exists either.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  const isSidebarCollapsed =
    cookieStore.get("sb-main-sidebar-collapsed")?.value === "true";
  const themeCookie = cookieStore.get("sb-theme")?.value;
  const isDark = themeCookie !== "light";

  // Resolve user + profile in parallel; if the account is deleted we must
  // redirect synchronously, so we await here (not in a stream).
  const user = await userPromise;

  let isAdmin = false;
  let isFrozen = false;
  let unreadMessages = 0;
  let unreadNotifications = 0;
  let avatarUrl: string | null = null;

  if (user) {
    await ensureUserProfile(user);
    const dbUser = await prisma.user.findUnique({
      where: { id: user.id },
      select: {
        isAdmin: true,
        avatarUrl: true,
        isFrozen: true,
        isDeleted: true,
        deletedByType: true,
      },
    });

    if (dbUser?.isDeleted) {
      const supabase = await createClient();
      await supabase.auth.signOut();
      if (dbUser.deletedByType === "ADMIN") {
        redirect("/login?error=account-deleted-by-admin");
      }
      redirect("/login?error=account-deleted");
    }

    const {
      unreadMessages: messageCount,
      unreadNotifications: notificationCount,
    } = await getUnreadCounts();

    isAdmin = dbUser?.isAdmin ?? false;
    isFrozen = dbUser?.isFrozen ?? false;
    unreadMessages = messageCount;
    unreadNotifications = notificationCount;
    avatarUrl = dbUser?.avatarUrl ?? null;
  }

  const sidebarUser = user
    ? { id: user.id, email: user.email, isAdmin, unreadMessages, avatarUrl }
    : null;

  return (
    <html
      lang="en"
      className={isDark ? "dark" : ""}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <head>
        {/* Synchronous, inline, and blocking on purpose: this is the earliest
            code we control, which is the only way to catch a
            `beforeinstallprompt` that fires before React hydrates. */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: INSTALL_PROMPT_CAPTURE }}
        />
      </head>
      <body className="min-h-screen bg-background font-sans antialiased text-foreground">
        <NextTopLoader showSpinner={false} />
        <AppProviders isFrozen={isFrozen}>
          {/* Owns the mobile nav drawer's open state so the shell column can
              mark itself `inert` while it is open. */}
          <NavigationDrawerProvider>
            <div className="relative flex min-h-screen w-full min-w-[var(--sb-min-viewport-width)] flex-col overflow-x-clip lg:h-dvh lg:min-h-0 lg:flex-row lg:overflow-hidden">
              <Sidebar user={sidebarUser} defaultCollapsed={isSidebarCollapsed} />

              {/* `inert` while the drawer is open: nothing in this column can be
                  clicked, tabbed to, or read out — so a tap outside the drawer
                  lands on the scrim and dismisses it, instead of activating a
                  kebab menu or dropdown floating above the dimmed page. */}
              <InertWhenDrawerOpen className="flex min-w-0 w-full flex-1 flex-col overflow-x-clip lg:min-h-0 lg:overflow-hidden">
                {isFrozen && (
                  <div
                    role="alert"
                    className="flex shrink-0 items-center justify-center gap-2 border-b border-amber-200 bg-amber-50 px-4 py-2 text-center text-sm font-semibold text-amber-800 dark:border-amber-900 dark:bg-amber-950/60 dark:text-amber-300"
                  >
                    <span aria-hidden>❄</span>
                    Your account is frozen. You can still browse, but posting,
                    commenting, voting, reporting and other interactions are
                    disabled until a moderator reviews your account.
                  </div>
                )}

                <Navbar user={user} unreadCount={unreadNotifications} />

                {/* Desktop-only inner scroll: on md+ only this <main> scrolls, so the
                    navbar + footer stay pinned and the scrollbar track spans just
                    the middle column. Mobile keeps native window scroll. */}
                <main
                  id="sb-main-scroll"
                  className="sb-shell w-full min-w-0 flex-1 grow py-4 lg:min-h-0 lg:overflow-y-auto lg:overscroll-contain lg:py-10"
                >
                  {children}
                </main>

                <ConditionalFooter />
              </InertWhenDrawerOpen>
          </div>
          </NavigationDrawerProvider>
        </AppProviders>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
